apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: onv3j1kaa-java-springboot 
  janus-idp.io/tekton: onv3j1kaa-java-springboot
  backstage.io/kubernetes-id: onv3j1kaa-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: onv3j1kaa-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml